/******************************************************************************
*   File:   MyDispids.h
*
*   Date:   March 13, 1998
*
*   Description:   This file contains the dispid's of the events which can
*               be defined in the script.  These dispid's are defined so
*               they can be fired easily from objects in the host.
*
*   Modifications:
******************************************************************************/
#define DISPID_ONSONGCHANGE 10
